### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createInvoice')

### ISSUE THREAD

**Issue by qhoarau** [dveldhoen/easyinvoice#101]
I'm using easyinvoice with nodejs, typescript and firebase cloud functions but when I call easyinvoice.createInvoice I have this error : 
TypeError: Cannot read properties of undefined (reading 'createInvoice')

sample code : 
import easyinvoice from "easyinvoice"; 
const data = {};
const generateInvoice = async () => {
   const result = await easyinvoice.createInvoice(data);
}

Version : 
"easyinvoice": "^3.0.23",
"node": "16",
"typescript": "^4.9.0"

**Comment by dveldhoen** [comment]
Hi, sorry for the late response. We will have a look and see if we can reproduce.

**Comment by dveldhoen** [comment]
I'm testing with:
"easyinvoice": "^3.0.23",
"node": "18",
"typescript": "^5.1.3"
  
 Which gives me no errors.
 
 This is my tsconfig, perhaps taking some options from here will fix your problem:
```json
 {
  "compilerOptions": {
    /* Language and Environment */
    "target": "es2016",

    /* Modules */
    "module": "commonjs",
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

Since it seems to be working on a clean project with the latest version I'm not sure how I can reproduce your issue. Either I will need more data or you can provide me with a sample repo which I can clone and test. Please let me know how you want to proceed.
