### ISSUE TITLE
Question about payments

### ISSUE THREAD

**Issue by snakysnake** [dveldhoen/easyinvoice#122]
Hello dear @dveldhoen!

I have a question: When using the package itself, is there some rate limit imposed on my project or is it just being ran locally? So basically the question would come down to: Does using this package come with cost when it's running on my own server?
I hope not, I like using this package, I think it's probably a fair amount for an API but would be way to much for me for software running on my end.

Dear regards,
Snakysnake

**Comment by dveldhoen** [comment]
Hi, thanks for contacting. It's indeed an API, all the logic and heavy lifting runs on our servers. Currently the rate limit is about 100 invoices/15 minutes, but will soon be aligned with what is posted on NPM 50 invoices/month. For $17,99 you can use it without limits. Please let me know if you need help setting up the apiKey with the paid version. We would greatly appreciate your use of our paid version, since it helps us fund new features. Some great ones are coming soon! Like adding discount and the option to set prices with tax either included or excluded. Kind regards!
