### ISSUE TITLE
Run this locally?

### ISSUE THREAD

**Issue by ensctom** [dveldhoen/easyinvoice#4]
Hi,

First of all, nice library. Just a few concerns.

I noticed that your createInvoice function is making a call to `'https://api.factuursimpel.nl/v1/invoices';` I'm worried about data harvesting as well as a dependency to some external api which I have no control over. Is there a way to create invoice locally?

**Comment by dveldhoen** [comment]
Hi there!

Thank you, always nice to hear! We will keep improving this package greatly so stay tuned!

I understand your concern. I can assure you there is nothing to worry about. We are a European based digital invoicing company that decided to share our invoice generation features with the world. Our hq is based in The Netherlands so this is where the '.nl' api domain comes from. This will soon be changed to 'api.easyinvoice.cloud' to show our global dedication. The api itself is already globally accelerated, capabale of millions of invoice generations per second. Regardless of continent. We are guaranteeing a 99,99% availability, so don't worry about any downtime.

Of course to keep our intellectual property inside the company we decided not to share our precious code that actually creates the invoices publicly. Since we also sell our features as a GUI, for now in Europe and soon Global.

The invoices that are generated will only be stored to serve the purpose of consolidation for the actual user of the api itself. This means that (soon) if you call 'easyinvoice.listInvoices()' you will get a list of your generated invoices by means of a secure api key. The invoices are stored securely, fully encrypted and will not be publicly accessible now or in the future. Your data will not be used by or sold to any 3rd parties.

Hopefully this answers your questions and takes away your concerns.

Kind regards!

**Comment by dlh2** [comment]
This is really important to notify in the NPM repository or the GitHub itself.

As some developers need the packages and with the current GDPR Europe Laws we can't make this into production without a signed agreement between the two companies.
