### ISSUE TITLE
API Handling

### ISSUE THREAD

**Issue by Tolfx** [dveldhoen/easyinvoice#48]
Due to the new update, all of our invoices which got sent was broken due to the new `API` was updated, and since we had the "old" config everything was broken.

We had to fix the code and resend all of our invoices twice which is a bummer...

Thus I recommend version handling, to not get these mistakes. So when a new version of the `NPM` comes out, it changes version to the correct one, and not the whole `API`.

**Comment by dveldhoen** [comment]
Our sincere apologies, we should have changed the major version instead of the minor. We were a bit to enthousiastic to bring our users the new v2 features. The API does use another endpoint, but we should have linked it to a major release.

We unpublished the minor releases 1.1.0 and 1.1.1 and published our new version under 2.0.0. 

I do recommend to migrate to 2.0.0 since the v1 endpoint will be depcrecated 1st of april 2022. It's only a matter of renaming and restructuring the input data object, shouldn't take more than a few minutes. The backend architecture is a lot more efficiënt and stable with v2.

Thank you for letting us know. We hope this fix will be on time to prevent other users from encountering the same problem.
