### ISSUE TITLE
npm install deprecated dependencies which have potential vulnerabilities

### ISSUE THREAD

**Issue by NicolasWent** [dveldhoen/easyinvoice#79]
Hello,

After doing npm install easyinvoice --save

I got the following error:
> 5 high severity vulnerabilities

It is due to deprecated dependency of a dependency of easyinvoice.

Do you have any potential fix for it?

**Comment by dveldhoen** [comment]
Hi, we updated the package with the following:
Updated dependencies, moved from webpack 4 to esbuild (this caused the high severity errors), moved from js to ts, updated eslint to v8. Due to the speed probably not entirely bugless, but it should solve your issues. Please let us know if you run into anything else.

**Comment by dveldhoen** [comment]
Please install the latest version of v3 for the latest changes.

**Comment by dveldhoen** [comment]
I'm curious. Have you had a chance to test?

**Comment by NicolasWent** [comment]
Hello,

Sorry, I did not tested it, I changed to a more lightweight way of generating invoices.
