### ISSUE TITLE
Background Image is not showing in reactjs

### ISSUE THREAD

**Issue by Talha-005** [dveldhoen/easyinvoice#86]
const [data, setData] = useState({
    images: {
      background: "https://public.easyinvoice.cloud/img/watermark-draft.jpg",
    },
    sender: {
      company: "",
      address: "",
      custom1: "", //phone
      custom2: "", //email
    },
    client: {
      company: "",
      address: "",
      custom1: "", //mobile
      custom2: "", //email
    },
    information: {
      number: "",
      date: `${moment().format("YYYY-MM-DD")}`,
      "due-date": `${moment().add(1, "days").format("YYYY-MM-DD")}`,
    },
    products: [
      {
        quantity: 1,
        description: "productName",
        price: 1,
        "tax-rate": 0,
      },
    ],
    settings: {
      currency: "USD",
      "tax-notation": "Tax",
    },
  })

  
  
  I am using this data, but background image is not being shown on pdf when I download.

**Comment by Kasrani** [comment]
It's the same thing in vueJS

**Comment by dveldhoen** [comment]
Are you aware that the 'draft' text is the background in this sample? 

Otherwise try using 'https://public.easyinvoice.cloud/pdf/sample-background.pdf' as per this sample: https://public.easyinvoice.cloud/json/easyinvoice-sample-background.json

Or your own image off course. Please let me know if this was a misunderstanding, or does the 'draft' text itself not show?

**Comment by dveldhoen** [comment]
I'm going to assume this isn't a problem anymore. Please reach out if anything is not working as expected.
