### ISSUE TITLE
Overall Tax and Discount

### ISSUE THREAD

**Issue by LouisMuriuki** [dveldhoen/easyinvoice#99]
Hello, thanks for this amazing package and help so far!
However, am looking for a way to add overall tax and discount(in either percentage or actual value ) to the SubTotal.
Can you shed some light on that.
Thank You

**Comment by dveldhoen** [comment]
Hi, thanks for contacting us. What do you mean by overall tax? Discount is not an option at the moment, but we will make sure to add it in a future release.

**Comment by Yoofi-A-Appiah** [comment]
Heyy, this is an amazing package. Any updates on when discount will be included please?

**Comment by jrsarath** [comment]
would love the discount feature, also support for client name/email along with address (currently supported)

**Comment by dveldhoen** [comment]
I guess we can't postpone this any longer since this is becoming the most asked feature 😇. We'll try to make a release in July.

**Comment by jrsarath** [comment]
would be really happy to contribute

**Comment by dveldhoen** [comment]
Much appreciated, but the invoice generation code is private. Since we sell it as a commercial product as well. Otherwise we would welcome the help.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: jrsarath ***@***.***>
Verzonden: Friday, June 23, 2023 8:57:08 AM
Aan: dveldhoen/easyinvoice ***@***.***>
CC: Danny Veldhoen ***@***.***>; State change ***@***.***>
Onderwerp: Re: [dveldhoen/easyinvoice] Overall Tax and Discount (Issue #99)


would be really happy to contribute

**Comment by sabatale** [comment]
Discounts per item and Discount on total would indeed be awesome!

**Comment by suyashvoso** [comment]
Hey please add discount feature without this invoice is **incomplete**. 
Discount should be percentage / rupees (flat rate) also don't skip these option while integration.

**Comment by dveldhoen** [comment]
I'm closing this for now. The feature has been moved to near the top of our new feature list, so you can expect us to work on it soon.
